### PR TITLE
add using backtics that are sometimes necessary in orient 2.1

### PR DESCRIPTION
**Pull request by wouterv**

### CODE REVIEW

**Comment by wouterv** [comment]
Perhaps you should put this as a new leading version and put the latest release in a branch as this change might not be compatible with orient 2.0.x

**Comment by raymanrt** [comment]
Very usefull, I didn't know it!

A good question for orientqb has always been the level of compatibility with orient versions.

Probably the best way is something like:
```
Query q = new Query();
q.setVersion(OrientVersion.V21X);
```

And your code could become:
```
if (this.getVersion().equals(OrientVersion.V21X) && reserved.contains(field.toLowerCase())) {
// ...
```

What do you think about it?

**Comment by wouterv** [comment]
My personal opinion is that you should use branches and not add these kinds of constructs to the code. You will drag them along forever and only to support an older version of orient that less and less people will use. 
My preference is branching the current master, giving it some meaningful name, like orient-2.1.x-support and change the version scheme in the pom to grossly match orients. So 2.0.something and release it to maven central
And allways use the master for the latests releases, so make that a 2.1.x version.
The 2.0 branches will probably never be touch again ever, unless somebody finds a real bug, then it can be updated and released seperately.

**Comment by wouterv** [comment]
Any chance of getting a release with this pull request?

**Comment by raymanrt** [comment]
You right Wouter, please give me only a few days.

Cheers,
   Riccardo

**Comment by raymanrt** [comment]
Hi,
  release done with some change.

I used the Token class to store the reserved keywords. I also fixed some typo in your code.

Let me know what you think about it.

**Comment by wouterv** [comment]
We got it into production without any troubles, so thanks!

**Pull request merged**
